root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
include_ext = ["go", "gohtml", "csv"]
exclude_dir = ["tmp", "vendor"]
delay = 500
stop_on_error = true
log = "air_errors.log"

[log]
time = true

[misc]
clean_on_exit = true
